# Generated by Django 5.0.7 on 2025-07-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uinfo',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uinfo',
            name='ph_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
